# Makefile.config

ifeq ($(HOSTNAME), workstation)
matlab_cmd = "/usr/local/MATLAB/R2019b/bin/matlab -nodesktop"
python_cmd = "python"
SHELL=/bin/bash
CONDAROOT = /usr/local/anaconda3/bin/anaconda
endif

ifeq ($(HOSTNAME), localhost)
matlab_cmd = "/Applications/MATLAB_R2019b.app/bin/matlab -nodesktop"
python_cmd = "python"
SHELL=/bin/bash
CONDAROOT = /usr/local/anaconda3/bin/anaconda
endif

.EXPORT_ALL_VARIABLES:

ifeq ($(HOSTNAME), workstation)
CODE_PATH = /home/user/code/
DATAROOT_PATH = ./data/raw
endif

ifeq ($(HOSTNAME), localhost)
CODE_PATH = /Users/user/MR/CODE/
DATAROOT_PATH = /Volumes/tume/ro/TUMGF-MRI/User/ProjectData/AwesomeProject/
endif